name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  Z4J_URL: ${{ secrets.ZENDESK_URL }}
  Z4J_TOKEN: ${{ secrets.ZENDESK_TOKEN }}
  Z4J_ADMIN_EMAIL: ${{ secrets.ZENDESK_ADMIN_EMAIL}}
  Z4J_AGENT_EMAIL: ${{ secrets.ZENDESK_AGENT_EMAIL}}
  Z4J_END_USER_EMAIL: ${{ secrets.ZENDESK_END_USER_EMAIL}}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # 4.3.0
      - name: Set up JDK 17
        uses: graalvm/setup-graalvm@7a1da54cb7fdef4ea19f6ecdfa9ecf59dc5a48fe # 1.3.6
        with:
          java-version: '17'
          distribution: 'graalvm-community'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # 4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # 4.3.0
      - name: Set up JDK 17
        uses: graalvm/setup-graalvm@7a1da54cb7fdef4ea19f6ecdfa9ecf59dc5a48fe # 1.3.6
        with:
          java-version: '17'
          distribution: 'graalvm-community'
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0