name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  MICRONAUT_HTTP_SERVICES_ZENDESK_EMAIL: ${{ secrets.ZENDESK_EMAIL}}
  MICRONAUT_HTTP_SERVICES_ZENDESK_TOKEN: ${{ secrets.ZENDESK_TOKEN}}
  MICRONAUT_HTTP_SERVICES_ZENDESK_URL: ${{ secrets.ZENDESK_URL}}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm-community'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm-community'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0